name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Check Ubuntu version
        run: |
          echo "Checking Ubuntu version..."
          lsb_release -a || cat /etc/os-release
          
      - name: Install dependencies
        run: npm ci

      - name: Start server in background
        run: |
          npm start &
          sleep 3  # Give it time to start

      - name: Test server is running
        run: curl http://localhost:3000/data


      # - name: Run lint (optional, if using ESLint)
      #   run: npm run lint
      #   continue-on-error: true  # Optional: avoid breaking the build for lint errors

      - name: Build the project (optional)
        run: npm run build --if-present

      # - name: Run tests
      #   run: npm test

      # - name: Deploy (optional)
      #   run: npm run deploy
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
